name 'dotnet-core'
maintainer 'Jose M. Tobar'
maintainer_email 'ilovemysillybanana@gmail.com'
license 'all_rights'
description 'Installs ASP.NET/.NET Core'
long_description 'Installs ASP.NET/.NET Core'
version '0.1.2'

supports 'ubuntu', '= 14.04'
supports 'ubuntu', '= 16.04'
supports 'ubuntu', '= 16.10'
supports 'fedora', '= 23'
supports 'fedora', '= 24'
supports 'centos', '>= 7.1'
supports 'oracle', '>= 7.1'
supports 'redhat', '>= 7.1'

depends 'yum', '~> 4.1.0'
depends 'apt', '~> 5.0.0'
depends 'sudo', '~> 3.1.0'
depends 'ohai', '~> 4.2.3'
