name 'dotnet'
maintainer 'Jose M. Tobar'
maintainer_email 'ilovemysillybanana@gmail.com'
license 'all_rights'
description 'Installs ASP.NET/.NET Core'
long_description 'Installs ASP.NET/.NET Core'
version '0.1.0'

depends 'yum'
depends 'apt'
depends 'sudo'
depends 'ohai'
